# Generated by Django 3.0.5 on 2020-04-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_art',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.URLField(),
        ),
    ]
